Welcome screen
praharsh05/kai-platform pull request #1
Opened 2024-08-09 17:51 UTC by Lamp-Nguyen

Implemented the UI for the welcome screen, including:
- Progress bar
- Welcome message
- Start button

2024-08-13 17:29 UTC, praharsh05 requested changes
Awesome Work @Lamp-Nguyen, you're on the right track! Just add comments to explain the code block and I think some changes need to be made for the StepProgressChecker or StepCompletedChecker as the terminal shows some warnings when running the app.

2024-08-13 17:29 UTC, praharsh05 commented on frontend/components/ProgressBar/ProgressBar.jsx
Add comments to explain the code blocks

2024-08-13 17:29 UTC, praharsh05 commented on frontend/templates/Onboarding/OnboardPage.jsx
> +          Welcome to <span style={{ color: '#8653FF' }}>KAI</span> 👋
move the color to styles

2024-08-15 12:08 UTC, peifangchiang commented
Great work! As @praharsh05 mentioned, there are some warnings in the terminal needed to solved.

2024-08-15 12:11 UTC, peifangchiang reviewed
Great work! As @praharsh05 mentioned, there are some warnings in the terminal needed to solved.

2024-08-20 23:01 UTC, praharsh05 approved these changes
Good Work @Lamp-Nguyen, let's move to finish the progress bar and take up other screens 🦾🦾

2024-08-20 23:02 UTC, merged